name: example-ngrok-kind-v2
on:
  workflow_dispatch:

jobs:
  example-ngrok-kind-v2:
    runs-on: ubuntu-latest
    steps:
    
      - name: SSH connection to Actions (cd openwrt && make menuconfig)
        uses: P3TERX/ssh2actions@v1.0.0
      
      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 300
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
          ngrok_addr_1: 88
          ngrok_proto_1: http
